<?php
include('filter_post_array.php');
$post_array=json_decode(urldecode($_POST['to_delete_pab']));
	$ajax_response=array();
	$post_array=check_filter_input($post_array);
if(isset($post_array)){
	if(isset($_COOKIE['hash'])){
		unset($_POST['to_delete_pab']);
		$hash_sess_id=$_COOKIE['hash'];
		include('sql_lib.php');
		$s_w=new sql_work();
		if($NP=$s_w->connect()){
			mysqli_autocommit($NP,false);
			include('get_user_id.php');
			if($user_id=get_user_id($NP,$s_w,$hash_sess_id,false,false)){
				if($user_id!=='not_able'){
					include('work_with_compressed_str.php');
					$type_str='';$q='';$query='';
					if($post_array->type_of_pab==='pablications'){
						$type_str='pabs';
						$q='pq';
						$query='UPDATE pablications SET isreadable=0, iswritable=0, path=? WHERE id=? LIMIT 1';
					}else{
						$type_str='copies';
						$q='cpq';
						$query='UPDATE copywritings SET isreadable=0,path=? WHERE id=? LIMIT 1';
					}
					if($compr_str=get_compressed_str($NP,$s_w,$user_id,$type_str,'ussd')){
						if($new_compr_str=delete_from_compressed_str($compr_str,$post_array->pab_id)){
							$spath_query='SELECT path FROM '.$post_array->type_of_pab.' WHERE id=? LIMIT 1';
							if($path_a=$s_w->get_info_in_new_array(
							$NP,
							$spath_query,
							array($post_array->pab_id),
							'i'
							)){
								$path='pabs/deleted_pab_by_user.html';
								if(update_compressed_str($NP,$s_w,$user_id,$type_str,'ussd',$new_compr_str,$q,'-')){
									if($s_w->manipulation(
									$NP,
									$query,
									array($path,$post_array->pab_id),
									'si'
									)){
										$ajax_response['info']=$path_a[0]['path'];
										file_put_contents($path_a[0]['path'],'');
										file_put_contents('mobile_'.$path_a[0]['path'],'');
										$deleting_path='http://paper-blog.ru'.$path_a[0]['path'];
										if(unlink($deleting_path)){
											$ajax_response['dinfo']='good';
										} 
										$ajax_response['status']='good';
										$ajax_response['pab_id']=$post_array->pab_id;
									}else{
                                        $ajax_response['status']='error#'.__LINE__;
									}
                               }else{
                               		$ajax_response['info']=$path_a[0]['path'];
                               		$ajax_response['status']='error#'.__LINE__;
							   }
                             }else{
								$ajax_response['status']='error#'.__LINE__;
							}
						}else{
							$ajax_response['status']='error#'.__LINE__;
					}}else{
						$ajax_response['status']='error#'.__LINE__;
				}}else{
					$ajax_response['status']='not_able';
			}}else{
				$ajax_response['status']='no_sess';
				setcookie('hash',$hash_sess_id, time()-3600, '/','.paper-blog.ru', false,true);
			}
			if($ajax_response['status']==='good'){
				mysqli_commit($NP);
			}else{
				mysqli_rollback($NP);
			}
			$s_w->sql_close($NP);
     }else{
       	$ajax_response['status']='error#'.__LINE__;
}}else{
	$ajax_response['status']='no_sess'; 
}
echo 'for(;;);'.json_encode($ajax_response); 
}
?>