<?php
include('filter_post_array.php');
$post_array=json_decode(urldecode($_POST['to_refresh_views']));
$post_array=check_filter_input($post_array);
if(isset($post_array)&&$post_array){
	if(isset($_COOKIE['hash'])){
	unset($_POST['to_refresh_views']);
	$ajax_response=array();
	$hash_sess_id=$_COOKIE['hash'];
	include('sql_lib.php');
	$s_w=new sql_work();
	if($NP=$s_w->connect()){
		mysqli_autocommit($NP,false);
		include('get_user_id.php');
		if($user_id=get_user_id($NP,$s_w,$hash_sess_id,false,false)){
			if($user_id!=='not_able'){
				include('work_with_compressed_str.php');
				$test=isset_elm_in_table($NP,$s_w,$post_array->pab_id,'pablications');
				if($test&&!empty($test)){
					if(($views_ussd_compressed_str=get_compressed_str($NP,$s_w,$user_id,'views','ussd'))
					&&($views_pablications_compressed_str=get_compressed_str($NP,$s_w,$post_array->pab_id,'views','pablications'))){
						if(($c1=add_to_compressed_str($views_ussd_compressed_str,$post_array->pab_id))&&
						($c2=add_to_compressed_str($views_pablications_compressed_str,$user_id))){
							if(update_compressed_str($NP,$s_w,$user_id,'views','ussd',$c1,'',0)){
								if(update_compressed_str($NP,$s_w,$post_array->pab_id,'views','pablications',$c2,'vq','+')){
									$ajax_response['status']='good';
                                }else{
                                	$ajax_response['status']='error#'.__LINE__;
								}}else{
									$ajax_response['status']='error#'.__LINE__;	
							}}else{
								$ajax_response['status']='good';
						}}else{
							$ajax_response['status']='error#'.__LINE__;
					}}else{
						$ajax_response['status']='error#'.__LINE__;
				}}else{
					$ajax_response['status']='not_able';
		}}else{
			$ajax_response['status']='no_sess'; 
			setcookie('hash',$hash_sess_id, time()-3600, '/','.paper-blog.ru', false,true);
		}
		if($ajax_response['status']==='good'){
			mysqli_commit($NP);
		}else{
			mysqli_rollback($NP);
		}
		$s_w->sql_close($NP);
     }else{
       	$ajax_response['status']='error#'.__LINE__;
}}else{
	$ajax_response['status']='no_sess'; 
}
echo 'for(;;);'.json_encode($ajax_response);
}
?>